name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend API
        - Frontend UI
        - Vector Database
        - Document Processing
        - Search Engine
        - Monitoring/Grafana
        - Docker/Infrastructure
        - Documentation
        - Other
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g. 3.11.5]
        - Node.js version: [e.g. 20.8.0]
        - Docker version: [e.g. 24.0.7]
        - Browser: [e.g. Chrome 118, Safari 17] (for frontend issues)
        - Vector DB Provider: [e.g. ChromaDB, Pinecone, Weaviate]
    validations:
      required: true
      
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, add error logs to help explain your problem
      placeholder: Paste any relevant error messages or logs here
      render: shell
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
          
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched the existing issues to make sure this bug hasn't been reported
          required: true
        - label: I have provided all the requested information
          required: true
        - label: I have tested this with the latest version
          required: false