name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install backend dependencies
        run: |
          cd backend
          PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 uv sync --dev

      - name: Run backend linting
        run: |
          cd backend
          uv run black . --check
          uv run isort . --check-only
          uv run flake8
          uv run mypy .

      - name: Run backend tests
        run: |
          cd backend
          uv run pytest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run frontend linting
        run: |
          cd frontend
          npm run lint

      - name: Run frontend build
        run: |
          cd frontend
          npm run build
